name: Practica Artifacts

on:
  push:

jobs:

  job-a:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Crear archivo
        run: |
          echo "Hola desde el Job A" > resultado.txt
          echo "Este archivo viajará al Job B"

      - name: Subir Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-archivo
          path: resultado.txt

  job-b:

    needs: job-a

    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v4
        with:
          name: mi-archivo

      - name: Ver contenido
        run: cat resultado.txt