name: Practica Secrets

on:
  push:

jobs:

  secretos:

    runs-on: ubuntu-latest

    steps:

      - name: Leer Secret
        run: |
          echo "$MENSAJE"

        env:
          MENSAJE: ${{ secrets.MENSAJE_SECRETO }}