name: Mi tercer Workflow

on:
  push:

jobs:
  explorando-maquina:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Mostrar carpeta actual
        run: pwd

      - name: Mostrar archivos
        run: ls -la

      - name: Leer README
        run: cat README.md

      - name: Mostrar contenido de .github
        run: ls -la .github

      - name: Mostrar contenido de workflows
        run: ls -la .github/workflows

      - name: Ver historial
        run: git log --oneline

      - name: Contar commits
        run: git rev-list --count HEAD

        